<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1" tests="3" time="0.069" ignored="0" failures="1" timestamp="13 Feb 2018 20:36:33 GMT" skipped="1" hostname="DESKTOP-HAHT87R" errors="0">
  <testcase name="testA" time="0.051" classname="com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1"/>
  <testcase name="testB" time="0.013" classname="com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1">
    <failure type="java.lang.AssertionError" message="TestB failed">
      <![CDATA[java.lang.AssertionError: TestB failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1.testB(ListenerOverirdeMethodsUse1.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase name="testC" time="0.005" classname="com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1">
    <skipped/>
  </testcase> <!-- testC -->
</testsuite> <!-- com.qtpselenium.selenium.TV9Part5.ListenerOverirdeMethodsUse1 -->
